exchange: binance
symbol: BTCUSDT
redis_url: redis://redis:6379/0
max_spread: 5.0  # ticks
# take profit / stop loss in fractions
tp: 0.006
sl: 0.003
signal_threshold: 0.5
ladder: [0.25, 0.25, 0.25, 0.25]
ladder_step: 0.1
qty: 0.001
adaptive_stop_k: 1.3
min_stop: 0.0006
api_url: https://fapi.binance.com
