# Application configuration

exchange_mode: live_paper  # live_paper | live_real
market:
  use: bybit_v5   # binance_futs | bybit_v5 | fake
  symbols: [BTCUSDT]
  binance_ws_public: wss://fstream.binance.com/stream
  bybit_ws_public:   wss://stream.bybit.com/v5/public

redis:
  url: ${REDIS_URL:-redis://localhost:6379/0}

collector:
  depth_levels: 10
  ws:
    binance:
      url: wss://fstream.binance.com/stream
    bybit:
      url: wss://stream.bybit.com/v5/public/linear
  reconnect_backoff_ms: [500, 1000, 2000, 5000]
  rate_limit_per_sec: 20

signal_engine:
  features:
    depth_top_k: 5
    sigma_window_ms: 1500
    ofi_window_ms: 1000
    ema_window_ms: 2000
  rules:
    min_liquidity: 0.5
    max_spread_ticks: 3
    sigma_min: 0.0
    sigma_max: 1.0
    ofi_buy_min: 0.001
    ofi_sell_min: 0.001
    qi_min: -1.0
    use_trend: false
  scoring:
    weights:
      spread: -0.2
      sigma: 0.3
      ofi: 0.3
      qi: 0.2
      depth: 0.2
    theta_emit: 0.6
  tp_pct: 0.006
  sl_pct: 0.003

ai_scorer:
  model_path: /app/models/seq_model.onnx
  threshold: 0.55
  batch_size: 32
  window:
    frequency_hz: 50
    seconds: 2
    depth_levels: 10

executor:
  ladder:
    fractions: [0.25, 0.25, 0.25, 0.25]
    step_ticks: 2
    use_percent: false
  tif: GTC
  post_only: true
  cancel_timeout_ms: 2500
  retry_backoff_ms: [200, 400, 800, 1600]
  adaptive_stop_k: 2.0
  min_stop: 0.002

signals:
  tp_pct: 0.006
  sl_pct: 0.003
  score_threshold: 0.65
  sigma_window_ms: 1500
  sigma_min: 0.0004
  sigma_max: 0.0020
  ofi_thr: 0.10
  qi_thr:  0.05
  ladder: [0.25, 0.25, 0.25, 0.25]
  ladder_step_ticks: 1

execution:
  mode: paper
  simulator:
    seed: 42
    base_latency_ms: 15
    latency_jitter_ms: [2, 8]
    maker_fill_model: queue
    taker_slip_bps: [1.0, 4.0]
    maker_fill_boost_if_qi: 0.15
    min_partial_fill_qty: 0.25
    cancel_timeout_ms: 800
    shock_prob: 0.0005
    shock_return: [-0.03, -0.10]
    liquidity_degrade_curve:
      x: [10000, 50000, 200000, 1000000]
      y_bps: [1.5, 3.0, 6.0, 20.0]

risk:
  enable: true

monitor:
  http_host: 0.0.0.0
  http_port: 8000
