BTCUSDT:
  tick_size: 0.1
  lot_step: 0.001
  min_qty: 0.001
  min_notional: 5.0
  maker_fee: 0.0002
  taker_fee: 0.0004
  mmr: 0.004
ETHUSDT:
  tick_size: 0.05
  lot_step: 0.001
  min_qty: 0.001
  min_notional: 5.0
  maker_fee: 0.0002
  taker_fee: 0.0004
  mmr: 0.005
