enable: true
daily_loss_cap_usd: 500.0
loss_streak_max: 3
session_cooldown_minutes: 60
precision:
  window: 50
  min_precision: 0.55
  safety_precision: 0.5
  freeze_step: 0.02
  consecutive_windows: 2
markout:
  window: 30
  min_markout: 0.0
volatility:
  enabled: true
  max_consecutive: 3
  precision_floor: 0.5
  debounce_ms: 60000
trade_cluster:
  enabled: false
  window_ms: 60000
  max_trades: 3
  cumulative_loss: -0.0005
near_liq_guard:
  enabled: true
  sl_buffer_multiplier: 1.5
